bemorecrm/bemorecrm/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

bmocrm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import landing_page


urlpatterns = [
    path('',landing_page, name="landing_page"),                                      # http://127.0.0.1:8000/            home page
    path('admin/', admin.site.urls),                            # http://127.0.0.1:8000/admin/
    path('leads/', include('leads.urls', namespace="leads"))    # http://127.0.0.1:8000/leads/
]

leads/urls.py
from django.urls import path

from .views import lead_list, lead_detail, lead_create, lead_update, lead_delete

app_name = "leads"


urlpatterns = [
    path('',lead_list, name= 'lead_list'),                          # http://127.0.0.1:8000/leads/              - default leads landing page 
    path('create/', lead_create, name= 'lead_create'),              # http://127.0.0.1:8000/leads/create/
    path('<int:pk>/', lead_detail, name= 'lead_detail'),            # http://127.0.0.1:8000/leads/1/            - shows details for each lead 
    path('<int:pk>/update/',lead_update, name= 'lead_update'),      # http://127.0.0.1:8000/leads/1/update/ 
    path('<int:pk>/delete/', lead_delete, name= 'lead_delete')      # http://127.0.0.1:8000/leads/1/delete/ 
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.



#----- Get build in user model
class User(AbstractUser):
    pass



class Lead(models.Model):

    #--------------------------------------------------------------------------Create Columns
    #----- Basic User names
    first_name  :str    = models.CharField(max_length=40)
    last_name   :str    = models.CharField(max_length=30)
    age         :int    = models.IntegerField(default=0)

    #----- link an agent to each lead created
    agent = models.ForeignKey("Agent", on_delete=models.CASCADE)


    #----- add a default viewing option when print the Agent class
    def __str__(self):
        return f"{self.first_name} {self.last_name}"




class Agent(models.Model):

    #----- decide what happens to an agent when a lead is deleted.
    user = models.OneToOneField("User", on_delete=models.CASCADE)


    #----- add a default viewing option when print the Agent class
    def __str__(self):
        return self.user.email

leads/forms.py
from django import forms
from .models import Lead

class LeadForm(forms.Form):
    first_name  :str    = forms.CharField()
    last_name   :str    = forms.CharField()
    age         :int    = forms.IntegerField(min_value=0)


# Uses the lead models template to build a table and form:
class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent'
        )

leads/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Lead
from .models import Agent
from .forms import LeadForm, LeadModelForm


# Create your views here.
def landing_page(request):
    return render(request, "landing.html")


def lead_list(request):

    leads = Lead.objects.all()
    context = {  "leads" : leads  }



    # return HttpResponse("Hello World")
    return render(request, "leads/lead_list.html",context)


def lead_detail(request, pk):

    lead = Lead.objects.get(id=pk)
    context = {  "lead" : lead  }
    return render(request, "leads/lead_detail.html",context)



def lead_create(request):
    form = LeadModelForm()

    if request.method == "POST":        #Proccess the form
        print('Receiving a post request')
        form = LeadModelForm(request.POST)

        if form.is_valid():
            print("The form is valid")

            form.save()

            print("Lead has been created")
            return redirect("/leads/")

    context = {
        "form": form
    }
    return render(request, "leads/lead_create.html", context)



def lead_update(request, pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)

    if request.method == "POST":        #Proccess the form
        print('Receiving a post request')
        form = LeadModelForm(request.POST, instance=lead)

        if form.is_valid():
            print("The form is valid")

            form.save()

            print("Lead has been created")
            return redirect(f"/leads/{pk}")

    
    context = {
        "form": form,
        "lead":lead
    }
    return render(request, "leads/lead_update.html", context)



def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/leads/")

leads/templates/leads/lead_create.html
{% extends "base.html" %}

{% block content %}

    <a href="{% url 'leads:lead_list' %}">Go back to leads</a>
    <hr />
    <h1>Create a new lead</h1>
    <form method="post"> 
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}

{% block content %}

<!------------------------------------------------------------------------------------------------------------------------------------>
    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
            <div class="flex mb-4">
                <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Overview
                </a>
                <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Reviews
                </a>
                <a href="{% url 'leads:lead_update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
            <div class="flex border-t border-gray-200 py-2">
                <span class="text-gray-500">Age</span>
                <span class="ml-auto text-gray-900">{{lead.age}}</span>
            </div>
            <div class="flex border-t border-gray-200 py-2">
                <span class="text-gray-500">Location</span>
                <span class="ml-auto text-gray-900">Dummy Location</span>
            </div>
            <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                <span class="text-gray-500">Cell phone</span>
                <span class="ml-auto text-gray-900">074 098 2752</span>
            </div>
            <div class="flex">
                <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
                <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                    <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                </svg>
                </button>
            </div>
            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
        </div>
        </div>
    </section>
<!------------------------------------------------------------------------------------------------------------------------------------>


    <a href="{% url 'leads:lead_list' %}">Go back to leads</a>
    <hr />
    <h1>This is the details of {{lead.first_name}}</h1>
    <p>This person's age: {{lead.age}}</p>
    <P>The agent responsible for this lead is: {{lead.agent}}</P>
    <hr />
    <a href="{% url 'leads:lead_update' lead.pk %}">Update</a>
    <a href="{% url 'leads:lead_delete' lead.pk %}">Delete</a>
    
{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}

{% block content %}

<!------------------------------------------------------------------------------------------------------------------------------------>
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">

        <div class="flex justify-between items-center w-full mb-10">
            <div>
                <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900">
                    Leads
                </h1>
            </div>
            <div>
                <a href="{% url 'leads:lead_create' %}" class="text-s text-indigo-500 hover:text-blue-500 tracking-widest font-medium title-font mb-1">
                    Create New Lead
                </a>
            </div>
        </div>
        <hr />
        <br />

        <div class="flex flex-wrap -m-4">
            {% for lead in leads %}
            <div class="p-4 md:w-1/3">
            <div class="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
                <div class="flex items-center mb-3">
                <div class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-indigo-500 text-white flex-shrink-0">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                    </svg>
                </div>
                <h2 class="text-gray-900 text-lg title-font font-medium">
                    {{lead.first_name}} {{lead.last_name}}
                </h2>
                </div>
                <div class="flex-grow">
                <p class="leading-relaxed text-base">
                    DESCRIPTION: New incoming lead
                </p>
                <a href="{% url 'leads:lead_detail' lead.pk%}" class="mt-3 text-indigo-500 inline-flex items-center">
                    View Lead
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                </a>
                </div>
            </div>
            </div>
            {% endfor %}
        </div>
        </div>
    </section>          
<!------------------------------------------------------------------------------------------------------------------------------------>

{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}

{% block content %}

<!------------------------------------------------------------------------------------------------------------------------------------>
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
            <a  href="{% url 'leads:lead_detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Overview
            </a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Reviews
            </a>
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Update Details
            </a>
        </div>
        <!--comment start 

        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{lead.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Location</span>
            <span class="ml-auto text-gray-900">Dummy Location</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Cell phone</span>
            <span class="ml-auto text-gray-900">074 098 2752</span>
        </div>
        <div class="flex">
            <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
            </button>
        </div>

        comment end-->
        <div class="flex flex-col">
            <form method="post" class="mb-4"> 
                {% csrf_token %}
                {{form.as_p}}
                <div class="flex justify-between mt-10">
                    <button type="submit" class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                        Submit
                    </button>
                    
                    <form method="POST" action="{% url 'leads:lead_delete' lead.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="text-white bg-red-800 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                            Delete
                        </button>
                    </form>
                    
                </div>
            </form>
        </div>
        

        
        

        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
    </div>
</section>
<!------------------------------------------------------------------------------------------------------------------------------------>

    <a href="{% url 'leads:lead_detail' lead.pk%}">Go back to {{lead.first_name}}'s profile</a>
    <hr />
    <h1>Update lead: {{lead.first_name}} {{lead.last_name}}</h1>
    <form method="post"> 
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>
    
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>bemocrm</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class = "max-w-7xl mx-auto">
        {% include 'nav_bar.html' %}
        {% block content %}

        {% endblock content %}
</body>
</html>

templates/landing.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            Be More CRM
        </h1>
        <p class="mb-8 leading-relaxed">
            Unify, Empower, Grow with Be More CRM. Welcome to Be More CRM - your one-stop solution for managing customer relationships. We integrate all your social and messaging platforms into one central hub, providing a comprehensive view of your customer interactions. Personalize customer service, streamline communication, and leverage data insights to boost sales growth. Start with Be More CRM today - your growth is our success. Let's 'be more' together.
        </p>
        
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
          <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/nav_bar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-blue-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">BE MORE</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <a href="{% url 'landing_page' %}" class="mr-5 hover:text-gray-900">Home</a>
      <a href="{% url 'leads:lead_list' %}" class="mr-5 hover:text-gray-900">Leads</a>
      <a class="mr-5 hover:text-gray-900">SIGN UP</a>
  
    </nav>
    <a# href="#" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
      LOGIN
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </button>
  </div>
</header>

templates/second_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Hello World</h1>
    <p>this is the second page</p>
    <ul>
        {% for lead in leads %}
        <li>{{lead}}</li>
        {% endfor %}

    </ul>
    {{leads}}
    
</body>